### ISSUE TITLE
Merge the scripts [DID & Payment] into placeholders in auto-mobile repo.

### ISSUE THREAD

**Issue by abhi3700** [subspace/auto-mobile#17]
TODO: 
- [x] Submit a PR.
- [ ] Ask @soufiane to verify its execution on the react-native runtime.
```[tasklist]
### Tasks
- [ ] https://github.com/subspace/auto-mobile/pull/15
- [ ] https://github.com/subspace/auto-mobile/pull/16
```
